[package]
name = "bevy_data_server"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_app = "0.15.3"
bevy_ecs = "0.15.3"
bevy_hierarchy = "0.15.3"
bevy_time = "0.15.3"
bevy_transform = "0.15.3"
chrono = "0.4.40"
csv = "1.3.1"
serde_json = "1.0.140"

[dev-dependencies]
bevy = "0.15.3"
